add_test([=[HamonCubeTest.Handles8NodeCube]=]  /home/seido/CLionProjects/hamon/hamon_tests [==[--gtest_filter=HamonCubeTest.Handles8NodeCube]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonCubeTest.Handles8NodeCube]=]  PROPERTIES WORKING_DIRECTORY /home/seido/CLionProjects/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonCubeTest.CorrectNeighborsForNode5]=]  /home/seido/CLionProjects/hamon/hamon_tests [==[--gtest_filter=HamonCubeTest.CorrectNeighborsForNode5]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonCubeTest.CorrectNeighborsForNode5]=]  PROPERTIES WORKING_DIRECTORY /home/seido/CLionProjects/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonCubeTest.ThrowsOnInvalidNodeCount]=]  /home/seido/CLionProjects/hamon/hamon_tests [==[--gtest_filter=HamonCubeTest.ThrowsOnInvalidNodeCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonCubeTest.ThrowsOnInvalidNodeCount]=]  PROPERTIES WORKING_DIRECTORY /home/seido/CLionProjects/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonNodeLogicTest.Serialization]=]  /home/seido/CLionProjects/hamon/hamon_tests [==[--gtest_filter=HamonNodeLogicTest.Serialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonNodeLogicTest.Serialization]=]  PROPERTIES WORKING_DIRECTORY /home/seido/CLionProjects/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonNodeLogicTest.DeserializationAndMerge]=]  /home/seido/CLionProjects/hamon/hamon_tests [==[--gtest_filter=HamonNodeLogicTest.DeserializationAndMerge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonNodeLogicTest.DeserializationAndMerge]=]  PROPERTIES WORKING_DIRECTORY /home/seido/CLionProjects/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  hamon_tests_TESTS HamonCubeTest.Handles8NodeCube HamonCubeTest.CorrectNeighborsForNode5 HamonCubeTest.ThrowsOnInvalidNodeCount HamonNodeLogicTest.Serialization HamonNodeLogicTest.DeserializationAndMerge)
