add_test([=[Hamon.NeighborsOutsideNodeThrows]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.NeighborsOutsideNodeThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.NeighborsOutsideNodeThrows]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.NeighborOutOfRangeThrows]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.NeighborOutOfRangeThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.NeighborOutOfRangeThrows]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.NeighborSelfLoopRemovedAndDeduped]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.NeighborSelfLoopRemovedAndDeduped]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.NeighborSelfLoopRemovedAndDeduped]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.ParseMinimalHypercube4]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.ParseMinimalHypercube4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.ParseMinimalHypercube4]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.ExplicitDimOk]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.ExplicitDimOk]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.ExplicitDimOk]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.ExplicitDimMismatchThrows]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.ExplicitDimMismatchThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.ExplicitDimMismatchThrows]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.NeighborsOverride]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.NeighborsOverride]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.NeighborsOverride]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.CpuParsing]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.CpuParsing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.CpuParsing]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.IpParsingExplicit]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.IpParsingExplicit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.IpParsingExplicit]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.MissingUseThrows]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.MissingUseThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.MissingUseThrows]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.BadDirectiveThrowsEarly]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.BadDirectiveThrowsEarly]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.BadDirectiveThrowsEarly]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.IncludeBasic]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.IncludeBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.IncludeBasic]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.IncludeWithVarsAndRelative]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.IncludeWithVarsAndRelative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.IncludeWithVarsAndRelative]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.LetExpansionInAutoAndIp]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.LetExpansionInAutoAndIp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.LetExpansionInAutoAndIp]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.RequireTruthyVar]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.RequireTruthyVar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.RequireTruthyVar]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.RequireFail]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.RequireFail]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.RequireFail]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.RequireComparisons]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.RequireComparisons]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.RequireComparisons]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Hamon.IncludeCircularDetected]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=Hamon.IncludeCircularDetected]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Hamon.IncludeCircularDetected]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonCubeTest.Handles8NodeCube]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=HamonCubeTest.Handles8NodeCube]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonCubeTest.Handles8NodeCube]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonCubeTest.CorrectNeighborsForNode5]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=HamonCubeTest.CorrectNeighborsForNode5]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonCubeTest.CorrectNeighborsForNode5]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonCubeTest.ThrowsOnInvalidNodeCount]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=HamonCubeTest.ThrowsOnInvalidNodeCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonCubeTest.ThrowsOnInvalidNodeCount]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonNodeLogicTest.Serialization]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=HamonNodeLogicTest.Serialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonNodeLogicTest.Serialization]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HamonNodeLogicTest.DeserializationAndMerge]=]  /home/seido/hamon/hamon_tests [==[--gtest_filter=HamonNodeLogicTest.DeserializationAndMerge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HamonNodeLogicTest.DeserializationAndMerge]=]  PROPERTIES WORKING_DIRECTORY /home/seido/hamon SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  hamon_tests_TESTS Hamon.NeighborsOutsideNodeThrows Hamon.NeighborOutOfRangeThrows Hamon.NeighborSelfLoopRemovedAndDeduped Hamon.ParseMinimalHypercube4 Hamon.ExplicitDimOk Hamon.ExplicitDimMismatchThrows Hamon.NeighborsOverride Hamon.CpuParsing Hamon.IpParsingExplicit Hamon.MissingUseThrows Hamon.BadDirectiveThrowsEarly Hamon.IncludeBasic Hamon.IncludeWithVarsAndRelative Hamon.LetExpansionInAutoAndIp Hamon.RequireTruthyVar Hamon.RequireFail Hamon.RequireComparisons Hamon.IncludeCircularDetected HamonCubeTest.Handles8NodeCube HamonCubeTest.CorrectNeighborsForNode5 HamonCubeTest.ThrowsOnInvalidNodeCount HamonNodeLogicTest.Serialization HamonNodeLogicTest.DeserializationAndMerge)
